import type { NotificationTemplate } from '../src/types';

export const defaultNotificationTemplates: NotificationTemplate[] = [
  {
    id: 'empresa-cadastrada',
    eventKey: 'EMPRESA_CADASTRADA',
    label: 'Nova empresa cadastrada',
    description: 'Enviada ao Super Admin e ao responsável quando uma empresa conclui o cadastro.',
    category: 'EMPRESA',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Novo cadastro de empresa — {empresa}',
    emailBody: 'Olá, {nome}. O cadastro da empresa {empresa} foi recebido e está aguardando análise.',
    whatsappBody: 'ELO LOG: o cadastro da empresa {empresa} foi recebido e está aguardando análise.',
    variables: ['nome', 'empresa', 'email', 'telefone']
  },
  {
    id: 'empresa-aprovada',
    eventKey: 'EMPRESA_APROVADA',
    label: 'Empresa aprovada',
    description: 'Enviada ao administrador da empresa quando o cadastro é liberado.',
    category: 'EMPRESA',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Cadastro aprovado — {empresa}',
    emailBody: 'Olá, {nome}. O cadastro da empresa {empresa} foi aprovado. Acesse a plataforma para começar.',
    whatsappBody: 'ELO LOG: o cadastro da empresa {empresa} foi aprovado. Você já pode acessar a plataforma.',
    variables: ['nome', 'empresa', 'link']
  },
  {
    id: 'usuario-cadastrado',
    eventKey: 'USUARIO_CADASTRADO',
    label: 'Usuário cadastrado',
    description: 'Enviada ao novo usuário e aos administradores responsáveis pelo tenant.',
    category: 'USUARIO',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Seu acesso ao Elo Log foi criado',
    emailBody: 'Olá, {nome}. Seu acesso à empresa {empresa} foi criado. Use o e-mail cadastrado para entrar.',
    whatsappBody: 'ELO LOG: seu acesso à empresa {empresa} foi criado. Use o e-mail cadastrado para entrar.',
    variables: ['nome', 'empresa', 'email', 'telefone', 'link']
  },
  {
    id: 'motorista-cadastrado',
    eventKey: 'MOTORISTA_CADASTRADO',
    label: 'Motorista cadastrado',
    description: 'Enviada ao motorista e aos administradores da empresa relacionada.',
    category: 'USUARIO',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Cadastro de motorista realizado',
    emailBody: 'Olá, {nome}. Seu cadastro como motorista na empresa {empresa} foi realizado.',
    whatsappBody: 'ELO LOG: seu cadastro como motorista na empresa {empresa} foi realizado.',
    variables: ['nome', 'empresa', 'email', 'telefone']
  },
  {
    id: 'frete-publicado',
    eventKey: 'FRETE_PUBLICADO',
    label: 'Frete publicado',
    description: 'Enviada aos motoristas elegíveis quando um novo frete fica disponível.',
    category: 'FRETE',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Novo frete disponível — {codigoFrete}',
    emailBody: 'Um novo frete ({codigoFrete}) foi publicado de {origem} para {destino}, no valor de {valor}.',
    whatsappBody: 'ELO LOG: novo frete {codigoFrete} disponível de {origem} para {destino}. Valor: {valor}.',
    variables: ['codigoFrete', 'origem', 'destino', 'valor', 'empresa', 'link']
  },
  {
    id: 'frete-aceito',
    eventKey: 'FRETE_ACEITO',
    label: 'Frete aceito',
    description: 'Enviada aos administradores da empresa e ao motorista responsável.',
    category: 'FRETE',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Frete {codigoFrete} aceito',
    emailBody: 'O frete {codigoFrete} foi aceito pelo motorista {nomeMotorista}.',
    whatsappBody: 'ELO LOG: o frete {codigoFrete} foi aceito pelo motorista {nomeMotorista}.',
    variables: ['codigoFrete', 'nomeMotorista', 'empresa', 'status']
  },
  {
    id: 'status-atualizado',
    eventKey: 'STATUS_ATUALIZADO',
    label: 'Status de frete atualizado',
    description: 'Enviada às pessoas envolvidas no frete quando o status muda.',
    category: 'FRETE',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Frete {codigoFrete}: status {status}',
    emailBody: 'O status do frete {codigoFrete} foi atualizado para {status}.',
    whatsappBody: 'ELO LOG: o frete {codigoFrete} foi atualizado para {status}.',
    variables: ['codigoFrete', 'status', 'empresa', 'nomeMotorista']
  },
  {
    id: 'frete-cancelado',
    eventKey: 'FRETE_CANCELADO',
    label: 'Frete cancelado',
    description: 'Enviada às pessoas envolvidas quando um frete é cancelado.',
    category: 'FRETE',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Frete {codigoFrete} cancelado',
    emailBody: 'O frete {codigoFrete} da empresa {empresa} foi cancelado. Motivo: {motivo}.',
    whatsappBody: 'ELO LOG: o frete {codigoFrete} foi cancelado. Motivo: {motivo}.',
    variables: ['codigoFrete', 'empresa', 'motivo', 'status', 'link']
  },
  {
    id: 'pagamento-criado',
    eventKey: 'PAGAMENTO_CRIADO',
    label: 'Cobrança de plano criada',
    description: 'Enviada ao administrador da empresa quando uma cobrança Asaas é criada.',
    category: 'PAGAMENTO',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Cobrança do plano criada — {empresa}',
    emailBody: 'A cobrança do plano {plano} para {empresa} foi criada no valor de {valor}.',
    whatsappBody: 'ELO LOG: a cobrança do plano {plano} para {empresa} foi criada no valor de {valor}.',
    variables: ['empresa', 'plano', 'valor', 'link']
  },
  {
    id: 'usuario-status-atualizado',
    eventKey: 'USUARIO_STATUS_ATUALIZADO',
    label: 'Status de usuário atualizado',
    description: 'Enviada ao usuário e aos administradores quando o status da conta muda.',
    category: 'USUARIO',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Atualização do seu acesso ao Elo Log',
    emailBody: 'Olá, {nome}. O status do seu acesso à empresa {empresa} foi atualizado para {status}.',
    whatsappBody: 'ELO LOG: o status do seu acesso à empresa {empresa} foi atualizado para {status}.',
    variables: ['nome', 'empresa', 'status', 'email', 'telefone', 'link']
  },
  {
    id: 'interesse-frete',
    eventKey: 'INTERESSE_FRETE',
    label: 'Interesse em frete e análise de vínculo',
    description: 'Enviada ao motorista quando a empresa atualiza a análise da solicitação de interesse ou vínculo.',
    category: 'FRETE',
    enabled: true,
    editable: true,
    channels: { email: true, whatsapp: true, inApp: true },
    emailSubject: 'Atualização da sua solicitação de frete',
    emailBody: 'Olá, {nome}. A empresa {empresa} atualizou sua solicitação para o frete {codigoFrete}: {status}.',
    whatsappBody: 'ELO LOG: sua solicitação no frete {codigoFrete} foi atualizada para {status} pela empresa {empresa}.',
    variables: ['nome', 'empresa', 'status', 'codigoFrete', 'link']
  },
  {
    id: 'login-otp',
    eventKey: 'LOGIN_OTP',
    label: 'Código de acesso por WhatsApp',
    description: 'Mensagem de autenticação enviada ao telefone informado no login. O código e a validade são obrigatórios.',
    category: 'SISTEMA',
    enabled: true,
    editable: true,
    channels: { email: false, whatsapp: true, inApp: false },
    emailSubject: 'Código de acesso',
    emailBody: 'Seu código de acesso é {codigo}. Válido por {validadeMinutos} minutos.',
    whatsappBody: '{nomePlataforma}: seu código de acesso é {codigo}. Válido por {validadeMinutos} minutos. Não compartilhe este código.',
    variables: ['nomePlataforma', 'codigo', 'validadeMinutos']
  },
  {
    id: 'erro-sistema',
    eventKey: 'ERRO_SISTEMA',
    label: 'Erro crítico do sistema',
    description: 'Mensagem técnica protegida; não pode ser editada nem usada para disparos comerciais.',
    category: 'SISTEMA',
    enabled: true,
    editable: false,
    systemLocked: true,
    channels: { email: false, whatsapp: false, inApp: true },
    emailSubject: 'Erro do sistema',
    emailBody: 'Ocorreu um erro interno. Consulte o log técnico com acesso autorizado.',
    whatsappBody: 'Ocorreu um erro interno no sistema.',
    variables: ['correlationId', 'timestamp']
  }
];
