import React, { useEffect, useState } from 'react';
import { FileText, Globe2, Lock, Plus, Save, Trash2 } from 'lucide-react';
import { api } from '../../services/api';
import { BlogPost, WebPage } from '../../types';

export const ContentManagementPanel: React.FC = () => {
  const [pages, setPages] = useState<WebPage[]>([]);
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [kind, setKind] = useState<'page' | 'post'>('page');
  const [selectedId, setSelectedId] = useState('');
  const [title, setTitle] = useState('');
  const [slug, setSlug] = useState('');
  const [excerpt, setExcerpt] = useState('');
  const [content, setContent] = useState('');
  const [author, setAuthor] = useState('');
  const [metaTitle, setMetaTitle] = useState('');
  const [metaDescription, setMetaDescription] = useState('');
  const [canonicalUrl, setCanonicalUrl] = useState('');
  const [coverImageUrl, setCoverImageUrl] = useState('');
  const [isPublished, setIsPublished] = useState(true);
  const [isIndexable, setIsIndexable] = useState(true);
  const [contentVersion, setContentVersion] = useState('');
  const [changeNote, setChangeNote] = useState('');
  const [legalHistory, setLegalHistory] = useState<Array<{ version: string; publishedAt: string; createdByName?: string; changeNote?: string }>>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<{ text: string; error?: boolean } | null>(null);
  const selected = (kind === 'page' ? pages : posts).find(item => item.id === selectedId) as (WebPage | BlogPost | undefined);
  const reset = () => { setSelectedId(''); setTitle(''); setSlug(''); setExcerpt(''); setContent(''); setAuthor(''); setMetaTitle(''); setMetaDescription(''); setCanonicalUrl(''); setCoverImageUrl(''); setIsPublished(true); setIsIndexable(true); setContentVersion(''); setChangeNote(''); setLegalHistory([]); };
  const load = async () => { setLoading(true); try { const [loadedPages, loadedPosts] = await Promise.all([api.getPages(), api.getPosts()]); setPages(loadedPages); setPosts(loadedPosts); } catch (error: any) { setNotice({ text: error.message || 'Não foi possível carregar os conteúdos.', error: true }); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const select = (item: WebPage | BlogPost, itemKind: 'page' | 'post') => { setKind(itemKind); setSelectedId(item.id); setTitle(item.title); setSlug(item.slug); setExcerpt(item.excerpt || ''); setContent(item.content); setAuthor('author' in item ? item.author : ''); setMetaTitle(item.metaTitle || ''); setMetaDescription(item.metaDescription || ''); setCanonicalUrl(item.canonicalUrl || ''); setCoverImageUrl(item.coverImageUrl || ''); setIsPublished(item.isPublished); setIsIndexable(item.isIndexable !== false); setContentVersion('contentVersion' in item ? item.contentVersion || '' : ''); setChangeNote(''); setLegalHistory([]); if (itemKind === 'page' && (item as WebPage).tenantId === null && ['termos-de-uso', 'politica-de-privacidade'].includes(item.slug)) void api.getPageVersions(item.id).then(result => setLegalHistory(result.versions || [])).catch(() => setLegalHistory([])); };
  const save = async (event: React.FormEvent) => {
    event.preventDefault(); setSaving(true); setNotice(null);
    try {
      const payload: Partial<WebPage & BlogPost> & { contentVersion?: string; changeNote?: string } = { title, slug, excerpt, content, metaTitle, metaDescription, canonicalUrl, coverImageUrl, isPublished, isIndexable }; if (kind === 'page' && ['termos-de-uso', 'politica-de-privacidade'].includes(slug)) { payload.contentVersion = contentVersion; payload.changeNote = changeNote; }
      if (kind === 'post') payload.author = author;
      if (selectedId) { kind === 'page' ? await api.updatePage(selectedId, payload) : await api.updatePost(selectedId, payload); }
      else { kind === 'page' ? await api.createPage(payload) : await api.createPost({ ...payload, author }); }
      await load(); reset(); setNotice({ text: 'Conteúdo salvo e publicado conforme a configuração.' });
    } catch (error: any) { setNotice({ text: error.message || 'Não foi possível salvar o conteúdo.', error: true }); }
    finally { setSaving(false); }
  };
  const remove = async () => { if (!selected || (selected as any).isSystemLocked || !window.confirm('Excluir este conteúdo?')) return; setSaving(true); try { kind === 'page' ? await api.deletePage(selected.id) : await api.deletePost(selected.id); await load(); reset(); setNotice({ text: 'Conteúdo excluído.' }); } catch (error: any) { setNotice({ text: error.message || 'Não foi possível excluir.', error: true }); } finally { setSaving(false); } };
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black text-slate-900 dark:text-white flex items-center gap-2"><FileText className="w-5 h-5 text-emerald-600" /> Conteúdo global do SaaS</h2><p className="text-xs text-slate-500 mt-1">O Super Admin pode editar todas as páginas e posts. Somente itens globais publicados e indexáveis aparecem no site público.</p></div><button type="button" onClick={reset} className="px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-bold flex items-center gap-2"><Plus className="w-4 h-4" /> Novo conteúdo</button></div>
    {notice && <div className={`rounded-lg px-3 py-2 text-xs font-semibold ${notice.error ? 'bg-rose-50 text-rose-800' : 'bg-emerald-50 text-emerald-800'}`}>{notice.text}</div>}
    <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-5"><aside className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-3 space-y-4"><div><p className="text-[10px] uppercase font-black text-slate-400 mb-2">Páginas</p>{loading ? <p className="text-xs text-slate-500">Carregando...</p> : pages.map(item => <button key={item.id} type="button" onClick={() => select(item, 'page')} className={`w-full text-left px-3 py-2 rounded-lg text-xs mb-1 flex items-center justify-between gap-2 ${selectedId === item.id ? 'bg-emerald-100 text-emerald-800' : 'hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-200'}`}><span className="truncate">{item.title}</span>{(item as any).isSystemLocked && <Lock className="w-3 h-3 shrink-0" />}</button>)}</div><div><p className="text-[10px] uppercase font-black text-slate-400 mb-2">Posts</p>{posts.map(item => <button key={item.id} type="button" onClick={() => select(item, 'post')} className={`w-full text-left px-3 py-2 rounded-lg text-xs mb-1 ${selectedId === item.id ? 'bg-emerald-100 text-emerald-800' : 'hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-200'}`}>{item.title}</button>)}</div></aside>
      <form onSubmit={save} className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 space-y-4"><div className="flex items-center justify-between gap-3"><div className="flex gap-2"><button type="button" onClick={() => { setKind('page'); reset(); }} className={`px-3 py-2 rounded-lg text-xs font-bold ${kind === 'page' ? 'bg-emerald-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>Página</button><button type="button" onClick={() => { setKind('post'); reset(); }} className={`px-3 py-2 rounded-lg text-xs font-bold ${kind === 'post' ? 'bg-emerald-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>Post</button></div>{(selected as any)?.isSystemLocked && <span className="text-[10px] font-bold text-slate-500 inline-flex items-center gap-1"><Lock className="w-3 h-3" /> Documento protegido contra exclusão</span>}</div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Título<input required value={title} onChange={e => setTitle(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label><label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Slug público<input required pattern="[a-z0-9-]+" value={slug} onChange={e => setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '-'))} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm font-mono" /></label><label className="sm:col-span-2 block text-xs font-bold text-slate-600 dark:text-slate-300">Resumo/descrição<textarea rows={2} value={excerpt} onChange={e => setExcerpt(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label>{kind === 'post' && <label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Autor<input value={author} onChange={e => setAuthor(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label>}<label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Título SEO<input value={metaTitle} onChange={e => setMetaTitle(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label><label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Canonical (opcional)<input type="url" value={canonicalUrl} onChange={e => setCanonicalUrl(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label><label className="sm:col-span-2 block text-xs font-bold text-slate-600 dark:text-slate-300">Descrição SEO<textarea rows={2} value={metaDescription} onChange={e => setMetaDescription(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label><label className="sm:col-span-2 block text-xs font-bold text-slate-600 dark:text-slate-300">Imagem social (opcional)<input type="url" value={coverImageUrl} onChange={e => setCoverImageUrl(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label></div>
        {kind === 'page' && selected && ['termos-de-uso', 'politica-de-privacidade'].includes(selected.slug) && <div className="sm:col-span-2 rounded-lg border border-amber-200 bg-amber-50/70 dark:bg-amber-950/20 dark:border-amber-900 p-3 space-y-3"><div className="text-[11px] font-bold text-amber-900 dark:text-amber-200">Governança do documento jurídico</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Nova versão<input value={contentVersion} onChange={e => setContentVersion(e.target.value)} placeholder="Ex.: 2026-08-27.2" maxLength={64} className="mt-1 w-full rounded-lg border border-amber-200 dark:border-amber-800 bg-transparent px-3 py-2 text-sm font-mono" /></label><label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Nota da alteração<input value={changeNote} onChange={e => setChangeNote(e.target.value)} placeholder="Resumo da revisão" maxLength={240} className="mt-1 w-full rounded-lg border border-amber-200 dark:border-amber-800 bg-transparent px-3 py-2 text-sm" /></label></div><p className="text-[10px] text-amber-800 dark:text-amber-300">Salvar publica a versão no cadastro e preserva um snapshot anterior. A revisão jurídica continua necessária antes de uso comercial definitivo.</p></div>}
        <label className="block text-xs font-bold text-slate-600 dark:text-slate-300">Conteúdo<textarea required rows={14} value={content} onChange={e => setContent(e.target.value)} placeholder="Texto ou HTML sanitizado" className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-transparent px-3 py-2 text-sm" /></label>
        {legalHistory.length > 0 && <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="text-[10px] uppercase font-black text-slate-400 mb-2">Histórico de versões anteriores</div><div className="space-y-1">{legalHistory.map(version => <div key={version.version + version.publishedAt} className="text-xs text-slate-600 dark:text-slate-300 flex flex-wrap justify-between gap-2"><span className="font-mono">v{version.version}</span><span>{new Date(version.publishedAt).toLocaleString()} · {version.createdByName || 'Super Admin'}</span><span>{version.changeNote || 'Sem nota'}</span></div>)}</div></div>}
        <div className="flex flex-wrap gap-5 text-xs font-semibold text-slate-700 dark:text-slate-200"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={isPublished} onChange={e => setIsPublished(e.target.checked)} className="rounded text-emerald-600" /> Publicado</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={isIndexable} onChange={e => setIsIndexable(e.target.checked)} className="rounded text-emerald-600" /> Indexável no buscador</label></div>
        <div className="rounded-lg bg-slate-50 dark:bg-slate-800/50 px-3 py-2 text-[10px] text-slate-500 flex gap-2"><Globe2 className="w-4 h-4 text-emerald-500 shrink-0" />{selected && ['termos-de-uso', 'politica-de-privacidade'].includes(selected.slug) ? 'Documento jurídico usado no cadastro; não indexável na vitrine pública.' : `URL pública: /${(selected as WebPage)?.publicPath === 'elo-log' ? 'elo-log' : 'conteudo'}/${slug || 'seu-slug'}`}</div><div className="flex justify-between gap-3 border-t border-slate-100 dark:border-slate-800 pt-4"><button type="button" onClick={remove} disabled={!selected || (selected as any).isSystemLocked || saving} className="px-4 py-2 rounded-lg border border-rose-200 text-rose-700 text-xs font-bold flex items-center gap-2 disabled:opacity-40"><Trash2 className="w-4 h-4" /> Excluir</button><button disabled={saving} className="px-5 py-2 rounded-lg bg-emerald-600 text-white text-xs font-bold flex items-center gap-2 disabled:opacity-50"><Save className="w-4 h-4" />{saving ? 'Salvando...' : selectedId ? 'Salvar alterações' : 'Criar conteúdo'}</button></div></form></div>
  </div>;
};
