import React, { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, Trash2 } from 'lucide-react';
import { api } from '../../services/api';
import { ErrorLogEntry } from '../../types';

export const ErrorLogPanel: React.FC = () => {
  const [items, setItems] = useState<ErrorLogEntry[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); try { const result = await api.getErrorLogs({ limit: 200 }); setItems(result.items); setTotal(result.total); } catch (error: any) { setNotice(error.message || 'Não foi possível carregar o log.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const cleanup = async () => { if (!window.confirm('Remover erros com mais de 90 dias?')) return; try { const result = await api.cleanupErrorLogs(90); setNotice(`${result.removed} registro(s) removido(s).`); await load(); } catch (error: any) { setNotice(error.message || 'Não foi possível aplicar a retenção.'); } };
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-800 dark:text-white uppercase tracking-wider flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-amber-500" /> Log de erros do sistema</h3><p className="text-[11px] text-slate-400 mt-1">Falhas técnicas são registradas de forma sanitizada. Tokens, senhas, códigos OTP e corpo de requisição não são armazenados.</p></div><div className="flex gap-2"><button type="button" onClick={() => void load()} className="px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-bold flex items-center gap-2"><RefreshCw className="w-4 h-4" /> Atualizar</button><button type="button" onClick={() => void cleanup()} className="px-3 py-2 rounded-lg border border-rose-200 text-rose-700 text-xs font-bold flex items-center gap-2"><Trash2 className="w-4 h-4" /> Reter 90 dias</button></div></div>{notice && <div className="rounded-lg bg-slate-100 dark:bg-slate-800 px-3 py-2 text-xs text-slate-700 dark:text-slate-200">{notice}</div>}<div className="rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden"><div className="px-4 py-3 bg-slate-50 dark:bg-slate-800/50 text-xs font-bold text-slate-600 dark:text-slate-300">{total} ocorrência(s) encontradas</div>{loading ? <div className="p-8 text-center text-xs text-slate-500">Carregando...</div> : items.length === 0 ? <div className="p-8 text-center text-xs text-emerald-700">Nenhum erro registrado.</div> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(item => <div key={item.id} className="p-4 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-slate-800 dark:text-white">{item.event || 'ERRO'}</strong><span className="text-slate-400">{new Date(item.createdAt).toLocaleString('pt-BR')}</span></div><p className="mt-1 text-slate-600 dark:text-slate-300">{item.message}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-slate-400"><span>Serviço: {item.service}</span><span>Rota: {item.method || ''} {item.route || ''}</span>{item.statusCode && <span>HTTP: {item.statusCode}</span>}<span>Correlação: {item.correlationId}</span></div></div>)}</div>}</div><p className="text-[10px] text-slate-500">Erros ocorridos somente no proxy Cloudflare podem não chegar ao servidor e, portanto, precisam ser consultados também nos registros do Cloudflare.</p></div>;
};
